spring:
  messages:
    basename: messages
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
      authorizationserver:
        client:
          product-hub-client:
            registration:
              client-id: ${PRODUCT_HUB_CLIENT_ID}
              client-secret: ${PRODUCT_HUB_CLIENT_SECRET}
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:${server.port}/login/oauth2/code/product-hub-client
              scopes:
                - user
              require-authorization-consent: true
server:
  port: 0
  servlet:
    context-path: /${spring.application.name}

feign:
  client:
    name: user-service